### ISSUE TITLE
`TimeoutFuture` isn't `Send`.

### ISSUE THREAD

**Issue by expenses** [rustwasm/gloo#109]
A `TimeoutFuture` isn't `Send` because a `wasm_bindgen::JsValue` isn't `Send`. `Send` is required for a lot of `Future` `Spawn`ers: https://docs.rs/futures/0.3.1/futures/task/trait.SpawnExt.html#method.spawn.

I'm not sure what the right fix for this is. This might be a situation where it's safe-enough to `unsafe impl Send`.

**Comment by expenses** [comment]
This can be fixed by using https://crates.io/crates/send_wrapper.

**Comment by Pauan** [comment]
You cannot use normal Future Spawners with wasm (this is because wasm currently does not support threads). Instead, you should use the `spawn_local` function in the [wasm-bindgen-futures](https://crates.io/crates/wasm-bindgen-futures) crate.

As for the more general problem of impling `Send`, that will likely never happen, because JS values fundamentally cannot be sent between threads (even when wasm eventually gets threads).

I've thought about implementing something similar to send_wrapper (thanks for the link), but that will have to wait until we have hands-on experience with wasm threads.
