### ISSUE TITLE
[feature request] Timers should be usable in Node.js environment

### ISSUE THREAD

**Issue by teohhanhui** [rustwasm/gloo#176]
### Describe the Bug

Trying to use timers while running in Node.js environment currently panics with: https://github.com/rustwasm/gloo/blob/2245cd9fde70ae35e3eebfa54e431077cffac2ea/crates/timers/src/callback.rs#L37

### Steps to Reproduce

N/A

### Expected Behavior

Timers work in Node.js environment.

### Actual Behavior

Panic with error message: `Only supported in a browser or web worker`

### Additional Context

Similar to #106

**Comment by teohhanhui** [comment]
Methods such as `set_timeout_with_callback_and_timeout_and_arguments_0` are only available from `web_sys`, which understandably does not support Node.js...

**Comment by PhilippGackstatter** [comment]
I would also like to have timers working in node.js because it is one of the blocking issues that prevents the `libp2p` crate from running in node.js. I'm prepared to work on this and was wondering if a fix would be accepted into the crate? I imagine I would need to use `js_sys` to call node.js's `setTimeout` function, but haven't gone deeper into the topic yet. Maybe @hamza1311 can comment on whether such a fix would be accepted and any pointers to get started? Thanks very much!

**Comment by hamza1311** [comment]
Assuming that `setTimeout` and `setInterval` are available in the global scope, we can use `wasm-bindgen` to import and use them.

```rust
#[wasm_bindgen]
extern {
    #[wasm_bindgen(...)]
    fn set_timeout(...) -> ...;

    #[wasm_bindgen(...)]
    fn set_interval(...) -> ...
}
```

See [relevant docs](https://rustwasm.github.io/wasm-bindgen/reference/attributes/on-js-imports/index.html)

Feel free to PR this, @PhilippGackstatter. I would be happy to merge it

**Comment by PhilippGackstatter** [comment]
Hey @hamza1311, would it be possible to publish a new `gloo-timers` version relatively soon, perhaps within the next week or so? We'd like to have this available on crates.io. Thanks!

**Comment by hamza1311** [comment]
@PhilippGackstatter just published a new patch version with this change.
