### ISSUE TITLE
gloo net add `.query` convenience method for `Request`

### ISSUE THREAD

**Issue by databasedav** [rustwasm/gloo#198]
## Summary

add `.query` convenience method for `Request`

## Motivation

makes sending query string parameters more ergonomic

## Detailed Explanation

right now, we must manually embed the query string into the request url, which isn't as ergonomic for an http library as, for example, [`reqwest`](https://docs.rs/reqwest/latest/reqwest/struct.RequestBuilder.html#method.query) with which you can do `.query(&[("key", "value")])`

## Drawbacks, Rationale, and Alternatives

i don't think there are drawbacks, refer to [`reqwest source`](https://docs.rs/reqwest/latest/src/reqwest/async_impl/request.rs.html#347) for implementation

## Unresolved Questions

**Comment by hamza1311** [comment]
Would you like to PR an implementation? Note that we should use the browser's API for building query parameters, [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) instead of adding a new dependency.

We should expose a wrapper around this API and use that wrapper for the `Request::query` method
