### ISSUE TITLE
UnwrapThrow vs console_error_panic_hook

### ISSUE THREAD

**Issue by David-OConnor** [rustwasm/gloo#31]
It appears that both [console_error_panic_hook](https://github.com/rustwasm/console_error_panic_hook) and [UnwrapThrowExt](https://docs.rs/wasm-bindgen/0.2.37/wasm_bindgen/trait.UnwrapThrowExt.html) accomplish the same thing; ie displaying panics in the browser console via `console.error`. [CONTRIBUTING.md](https://github.com/rustwasm/gloo/blob/master/CONTRIBUTING.md) directs `UnwrapThrowExt`. What do y'all think? What's `panic_hook`'s niche?

**Comment by Pauan** [comment]
If there is a panic that is *not* caused by `UnwrapThrowExt`, then the panic hook will catch it.

Since there are many crates that are not wasm-specific, it is common for regular panics to occur.

**Comment by David-OConnor** [comment]
Makes sense. How do you feel about ammending `CONTRIBUTING.md` to allow `panic_hook` in Gloo crates in lieu of `UnwrapThrowExt`?

**Comment by Pauan** [comment]
I don't think it's about "one or the other", since they serve different purposes:

* `unwrap_throw` is used to avoid string formatting, which makes the wasm binary sizes smaller.

* `console_error_panic_hook` is used to handle anything which isn't handled by `unwrap_throw` (e.g. third party crates, the stdlib, etc.)

So ideally, projects would use both.

Also, `console_error_panic_hook` is used by *applications*, it should not be used by libraries (like Gloo).

That's because it is run *once*, in the `main` function. Whereas `unwrap_throw` is put within the actual libraries themself.

**Comment by David-OConnor** [comment]
Makes sense, esp this part: 

> That's because it is run once, in the main function. Whereas unwrap_throw is put within the actual libraries themself.

**Comment by fitzgen** [comment]
Yep, `console_error_panic_hook` is for top-level crates: either the application of the crate that is being compiled into a wasm library for JS consumption.

Using `unwrap_throw` is an optimization that wasm-specific crates can use to get smaller code size when they must unwrap an option or result.

If you have docs improvement suggestions, please send a PR to `wasm-bindgen` and/or `console_error_panic_hook`! :)

@David-OConnor, do you feel like your question has been answered? Can we close this issue?

**Comment by David-OConnor** [comment]
Affirm
