### ISSUE TITLE
Server sent events library

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/gloo#8]
Perhaps something like https://github.com/yerkopalma/choo-sse?

Probably best expressed as a futures stream.

**Comment by dureuill** [comment]
Hello!

I have been following the Server-sent-events (SSE) libraries for yew closely, and I even built an [example](https://github.com/dureuill/yew-sse-example) of using [liquidnya/yew-sse](https://github.com/liquidnya/yew-sse) with yew 16.2, rocket 0.5-rc1 and trunk.

If I understand correctly, yew::services are being removed so that the yew crate can be thinner which will ease server-side-rendering (SSR)?

I'm unfamiliar with gloo, but willing to help to get SSE into yew. Is the correct way forward to open a PR against gloo? What about reqwasm that is mentioned in https://github.com/yewstack/yew/issues/1346#issuecomment-883469926? I'm a bit unfamiliar with the WASM ecosystem.
